=== asesorov/Driver-Attention-Monitor/configs/schemas/main_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "RESOURCES": {
            "type": "object",
            "properties": {
                "AUDIO_ALARM": {"type": "string"}
            },
            "required": ["AUDIO_ALARM"]
        },
        "THRESHOLDS": {
            "type": "object",
            "properties": {
                "EAR_THRESH": {
                    "type": "array",
                    "items": {"type": "number"}
                },
                "HEAD_THRESH": {
                    "type": "array",
                    "items": {"type": "number"}
                },
                "DROWSY_THRESH": {
                    "type": "array",
                    "items": {"type": "number"}
                },
                "WAIT_TIME": {
                    "type": "array",
                    "items": {"type": "number"}
                }
            },
            "required": ["EAR_THRESH", "HEAD_THRESH", "WAIT_TIME"]
        },
        "WEBRTC": {
            "type": "object",
            "properties": {
                "KEY": {"type": "string"},
                "VIDEO_HEIGHT": {"type": "number"}
            },
            "required": ["KEY", "VIDEO_HEIGHT"]
        },
        "DETECTION": {
            "type": "object",
            "properties": {
                "MEDIAPIPE": {
                    "type": "object",
                    "properties": {
                        "MAX_FACES": {"type": "number"},
                        "MIN_FACE_DETECTION_CONFIDENCE": {"type": "number"},
                        "MIN_FACE_TRACKING_CONFIDENCE": {"type": "number"}
                    },
                    "required": ["MAX_FACES", "MIN_FACE_DETECTION_CONFIDENCE", "MIN_FACE_TRACKING_CONFIDENCE"]
                },
                "OPENVINO": {
                    "type": "object",
                    "properties": {
                        "HEAD_POS_MODEL": {"type": "string"},
                        "HEAD_POS_MODEL_WEIGHTS": {"type": "string"},
                        "DROWSY_MODEL": {"type": "string"},
                        "DROWSY_MODEL_WEIGHTS": {"type": "string"},
                        "HEAD": {
                            "type": "object",
                            "properties": {
                                "IR": {
                                    "type": "string"
                                },
                                "WEIGHTS": {
                                    "type": "string"
                                },
                                "INPUT_NAME": {
                                    "type": "string"
                                },
                                "OUTPUT_NAME": {
                                    "type": "string"
                                }
                            },
                            "required": ["IR", "WEIGHTS", "INPUT_NAME", "OUTPUT_NAME"]
                        },
                        "DROWSY": {
                            "type": "object",
                            "properties": {
                                "IR": {
                                    "type": "string"
                                },
                                "WEIGHTS": {
                                    "type": "string"
                                },
                                "INPUT_NAME": {
                                    "type": "string"
                                },
                                "OUTPUT_NAME": {
                                    "type": "string"
                                }
                            },
                            "required": ["IR", "WEIGHTS", "INPUT_NAME", "OUTPUT_NAME"]
                        }
                    },
                    "required": ["HEAD", "DROWSY"]
                },
                "EAR": {
                    "type": "object",
                    "properties": {
                        "LANDMARKS": {
                            "type": "object",
                            "properties": {
                                "LEFT": {
                                    "type": "array",
                                    "items": {"type": "number"}
                                },
                                "RIGHT": {
                                    "type": "array",
                                    "items": {"type": "number"}
                                }
                            },
                            "required": ["LEFT", "RIGHT"]
                        }
                    },
                    "required": ["LANDMARKS"]
                }
            },
            "required": ["MEDIAPIPE", "OPENVINO", "EAR"]
        }
    },
    "required": ["RESOURCES", "THRESHOLDS", "WEBRTC", "DETECTION"]
}

=== asesorov/Driver-Attention-Monitor/configs/samples/default_config.json
{
    "RESOURCES":
    {
        "AUDIO_ALARM": "assets/wake_up.wav"
    },
    "THRESHOLDS":
    {
        "EAR_THRESH": [0.0, 0.4, 0.18, 0.01],
        "HEAD_THRESH": [0.0, 25.0, 15.0, 0.5],
        "DROWSY_THRESH": [0.0, 30.0, 15.0, 1.0],
        "WAIT_TIME": [0.0, 5.0, 1.0, 0.25]
    },
    "WEBRTC":
    {
        "KEY": "drowsiness-detection",
        "VIDEO_HEIGHT": 480
    },
    "DETECTION":
    {
        "MEDIAPIPE":
        {
            "MAX_FACES": 1,
            "MIN_FACE_DETECTION_CONFIDENCE": 0.5,
            "MIN_FACE_TRACKING_CONFIDENCE": 0.5
        },
        "OPENVINO":
        {
            "HEAD":
            {
                "IR": "models/head-pose-estimation-adas-0001/head-pose-estimation-adas-0001.xml",
                "WEIGHTS": "models/head-pose-estimation-adas-0001/head-pose-estimation-adas-0001.bin",
                "INPUT_NAME": "data",
                "OUTPUT_NAME": "angle_y_fc"
            },
            "DROWSY":
            {
                "IR": "models/mobilenetv3/mobilenet_v3_large.xml",
                "WEIGHTS": "models/mobilenetv3/mobilenet_v3_large.bin",
                "INPUT_NAME": "input.1",
                "OUTPUT_NAME": "519"
            },
            "HEAD_POS_MODEL": "models/head-pose-estimation-adas-0001/head-pose-estimation-adas-0001.xml",
            "HEAD_POS_MODEL_WEIGHTS": "models/head-pose-estimation-adas-0001/head-pose-estimation-adas-0001.bin",
            "DROWSY_MODEL": "models/mobilenetv3/mobilenet_v3_large.xml",
            "DROWSY_MODEL_WEIGHTS": "models/mobilenetv3/mobilenet_v3_large.bin"
        },
        "EAR":
        {
            "LANDMARKS":
            {
                "LEFT": [362, 385, 387, 263, 373, 380],
                "RIGHT": [33, 160, 158, 133, 153, 144]
            }
        }
    }
}
